# Generated by Django 3.2.4 on 2021-06-30 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatosColaboradores',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='RUT Colaborador')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre Colaborador')),
                ('telefono', models.CharField(max_length=9, verbose_name='Telefono Colaborador')),
                ('dir', models.CharField(max_length=100, verbose_name='Dirección Colaborador')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Colaborador')),
                ('pais', models.CharField(max_length=30, verbose_name='País Colaborador')),
                ('clave', models.CharField(max_length=50, verbose_name='Contraseña')),
                ('imagen', models.ImageField(upload_to='colaboradores/')),
            ],
        ),
    ]
